version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ../mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: ghcr.io/huginn/huginn-single-process
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql

  threaded:
    image: ghcr.io/huginn/huginn-single-process
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql
      - web

  execute_command:
    build: ./execute_command
    restart: always
    ports:
      - "3535:3535"
    depends_on:
      - threaded

volumes:
  mysql_data:
